POST https://swharden.com/activity/add/
Content-Type: application/json

{
  "ComputerId": "personal-laptop",
  "Secret": "secret123",
  "Day": "2026-03-05",
  "Hex": "0F441880044A0D020E80C8442B4004100559"
}